apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: url-shortener
data:
  APP_ENV: "dev"
  DB_PORT: "5432"
  DB_HOST: "arn:aws:secretsmanager:eu-west-2:703844615264:secret:DB_URL-CrV7Io"
  SQS_URL: "https://sqs.eu-west-2.amazonaws.com/703844615264/sqs-queue"
  SQS_DLQ_URL: "https://sqs.eu-west-2.amazonaws.com/703844615264/sqs-queue-dlq"