apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "url-shortener.fullname" . }}-worker-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.worker.irsaRoleArn }}"
