apiVersion: v1 
kind: ServiceAccount  
metadata: 
  name: worker-sa
  namespace: url-shortener
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::703844615264:role/worker-irsa-${var.environment}