apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: url-shortener
data:
  APP_ENV: "dev"
  DB_PORT: "5432"
  DB_HOST: "arn:aws:secretsmanager:eu-west-2:703844615264:secret:DB_URL-CrV7Io"
  REDIS_HOST: "shortener-redis-dev.mno1mk.0001.euw2.cache.amazonaws.com:6379"
  REDIS_PORT: "6379"