apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: url-shortener
data:
  APP_ENV: "dev"
  DB_HOST: "rds-db-dev.c9uu0o266g6u.eu-west-2.rds.amazonaws.com"
  DB_PORT: "5432"
  REDIS_HOST: "arn:aws:elasticache:eu-west-2:679930074435:cluster:shortener-redis-dev"
  REDIS_PORT: "6379"