apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-api-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.api.config.APP_ENV | quote }}
  DB_HOST: {{ .Values.api.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.api.config.DB_PORT | quote }}
  REDIS_HOST: {{ .Values.api.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.api.config.REDIS_PORT | quote }}
