apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
