apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "url-shortener.fullname" . }}-api-sa
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.api.irsaRoleArn }}"
