apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: url-shortener
data:
  APP_ENV: "dev"
  DB_PORT: "5432"
  DB_HOST: "rds-db-dev.c9uu0o266g6u.eu-west-2.rds.amazonaws.com"
  SQS_URL: "https://sqs.eu-west-2.amazonaws.com/679930074435/sqs-queue"
  SQS_DLQ_URL: "https://sqs.eu-west-2.amazonaws.com/679930074435/sqs-queue-dlq"