apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-worker-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.worker.config.APP_ENV | quote }}
  DB_PORT: {{ .Values.worker.config.DB_PORT | quote }}
  DB_HOST: {{ .Values.worker.config.DB_HOST | quote }}
  SQS_URL: {{ .Values.worker.config.SQS_URL | quote }}
  SQS_QUEUE_URL: {{ .Values.worker.config.SQS_QUEUE_URL | quote }}
  SQS_DLQ_URL: {{ .Values.worker.config.SQS_DLQ_URL | quote }}